version: "3.9"

# Environnement de DEVELOPPEMENT
# Lancer avec : docker compose -f docker-compose.dev.yml up --build

services:
  db:
    image: mysql:8
    container_name: mentora_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mentora
    ports:
      - "3306:3306"
    volumes:
      - mentora_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: mentora_adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mentora_backend_dev
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.development
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mentora_frontend_dev
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules   # 🔥 CRUCIAL
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true  # 🔥 important pour Docker

volumes:
  mentora_data:
