// Liste statique des indicatifs téléphoniques (pas d'appel API externe requis).
// Chaque entrée : code ISO2, nom (FR), indicatif (avec +), drapeau (emoji).
// La France est placée en premier pour être la valeur par défaut du sélecteur.
export const countries = [
  { iso: 'FR', name: 'France',                dial: '+33',  flag: '🇫🇷' },
  { iso: 'BE', name: 'Belgique',               dial: '+32',  flag: '🇧🇪' },
  { iso: 'CH', name: 'Suisse',                 dial: '+41',  flag: '🇨🇭' },
  { iso: 'LU', name: 'Luxembourg',             dial: '+352', flag: '🇱🇺' },
  { iso: 'MC', name: 'Monaco',                 dial: '+377', flag: '🇲🇨' },
  { iso: 'CA', name: 'Canada',                 dial: '+1',   flag: '🇨🇦' },
  { iso: 'US', name: 'États-Unis',             dial: '+1',   flag: '🇺🇸' },
  { iso: 'GB', name: 'Royaume-Uni',            dial: '+44',  flag: '🇬🇧' },
  { iso: 'DE', name: 'Allemagne',              dial: '+49',  flag: '🇩🇪' },
  { iso: 'ES', name: 'Espagne',                dial: '+34',  flag: '🇪🇸' },
  { iso: 'IT', name: 'Italie',                 dial: '+39',  flag: '🇮🇹' },
  { iso: 'PT', name: 'Portugal',               dial: '+351', flag: '🇵🇹' },
  { iso: 'NL', name: 'Pays-Bas',               dial: '+31',  flag: '🇳🇱' },
  { iso: 'MA', name: 'Maroc',                  dial: '+212', flag: '🇲🇦' },
  { iso: 'DZ', name: 'Algérie',                dial: '+213', flag: '🇩🇿' },
  { iso: 'TN', name: 'Tunisie',                dial: '+216', flag: '🇹🇳' },
  { iso: 'CI', name: "Côte d'Ivoire",          dial: '+225', flag: '🇨🇮' },
  { iso: 'SN', name: 'Sénégal',                dial: '+221', flag: '🇸🇳' },
  { iso: 'ML', name: 'Mali',                   dial: '+223', flag: '🇲🇱' },
  { iso: 'BF', name: 'Burkina Faso',           dial: '+226', flag: '🇧🇫' },
  { iso: 'BJ', name: 'Bénin',                  dial: '+229', flag: '🇧🇯' },
  { iso: 'TG', name: 'Togo',                   dial: '+228', flag: '🇹🇬' },
  { iso: 'NE', name: 'Niger',                  dial: '+227', flag: '🇳🇪' },
  { iso: 'GN', name: 'Guinée',                 dial: '+224', flag: '🇬🇳' },
  { iso: 'CM', name: 'Cameroun',               dial: '+237', flag: '🇨🇲' },
  { iso: 'GA', name: 'Gabon',                  dial: '+241', flag: '🇬🇦' },
  { iso: 'CD', name: 'RD Congo',               dial: '+243', flag: '🇨🇩' },
  { iso: 'CG', name: 'Congo',                  dial: '+242', flag: '🇨🇬' },
  { iso: 'MG', name: 'Madagascar',             dial: '+261', flag: '🇲🇬' },
  { iso: 'MU', name: 'Maurice',                dial: '+230', flag: '🇲🇺' },
  { iso: 'RE', name: 'La Réunion',             dial: '+262', flag: '🇷🇪' },
  { iso: 'HT', name: 'Haïti',                  dial: '+509', flag: '🇭🇹' },
  { iso: 'EG', name: 'Égypte',                 dial: '+20',  flag: '🇪🇬' },
  { iso: 'NG', name: 'Nigeria',                dial: '+234', flag: '🇳🇬' },
  { iso: 'GH', name: 'Ghana',                  dial: '+233', flag: '🇬🇭' },
  { iso: 'ZA', name: 'Afrique du Sud',         dial: '+27',  flag: '🇿🇦' },
  { iso: 'KE', name: 'Kenya',                  dial: '+254', flag: '🇰🇪' },
  { iso: 'IE', name: 'Irlande',                dial: '+353', flag: '🇮🇪' },
  { iso: 'AT', name: 'Autriche',               dial: '+43',  flag: '🇦🇹' },
  { iso: 'SE', name: 'Suède',                  dial: '+46',  flag: '🇸🇪' },
  { iso: 'NO', name: 'Norvège',                dial: '+47',  flag: '🇳🇴' },
  { iso: 'DK', name: 'Danemark',               dial: '+45',  flag: '🇩🇰' },
  { iso: 'FI', name: 'Finlande',               dial: '+358', flag: '🇫🇮' },
  { iso: 'PL', name: 'Pologne',                dial: '+48',  flag: '🇵🇱' },
  { iso: 'RO', name: 'Roumanie',               dial: '+40',  flag: '🇷🇴' },
  { iso: 'GR', name: 'Grèce',                  dial: '+30',  flag: '🇬🇷' },
  { iso: 'TR', name: 'Turquie',                dial: '+90',  flag: '🇹🇷' },
  { iso: 'RU', name: 'Russie',                 dial: '+7',   flag: '🇷🇺' },
  { iso: 'CN', name: 'Chine',                  dial: '+86',  flag: '🇨🇳' },
  { iso: 'JP', name: 'Japon',                  dial: '+81',  flag: '🇯🇵' },
  { iso: 'KR', name: 'Corée du Sud',           dial: '+82',  flag: '🇰🇷' },
  { iso: 'IN', name: 'Inde',                   dial: '+91',  flag: '🇮🇳' },
  { iso: 'AU', name: 'Australie',              dial: '+61',  flag: '🇦🇺' },
  { iso: 'BR', name: 'Brésil',                 dial: '+55',  flag: '🇧🇷' },
  { iso: 'MX', name: 'Mexique',                dial: '+52',  flag: '🇲🇽' },
  { iso: 'AE', name: 'Émirats arabes unis',    dial: '+971', flag: '🇦🇪' },
  { iso: 'SA', name: 'Arabie saoudite',        dial: '+966', flag: '🇸🇦' },
  { iso: 'LB', name: 'Liban',                  dial: '+961', flag: '🇱🇧' },
]

export const defaultCountry = countries[0] // France
